{
 "title": "Tiered Storage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({container=\"redpanda\"},instance)"
    }
   },
   { "name": "node_shard", "label": "Shard", "query": { "query": "label_values(shard)" } },
   {
    "name": "aggr_criteria",
    "label": "Aggregate by",
    "query": "cluster, pod, instance, shard, instance\\,shard, pod\\,shard"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Tiered Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upload speed (to tiered storage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vectorized_cloud_storage_bytes_sent{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}[5m])) by ([[aggr_criteria]])"
    }
   ]
  },
  {
   "title": "Download speed (from tiered storage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vectorized_cloud_storage_bytes_received{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}[5m])) by ([[aggr_criteria]])"
    }
   ]
  },
  {
   "title": "Rate of failed uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vectorized_cloud_storage_failed_uploads{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}[5m])) by ([[aggr_criteria]])"
    }
   ]
  },
  {
   "title": "Rate of failed downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vectorized_cloud_storage_failed_downloads{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}[$__rate_interval])) by ([[aggr_criteria]])"
    }
   ]
  },
  {
   "title": "Uploaded bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vectorized_ntp_archiver_uploaded_bytes{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}[5m])) by ([[aggr_criteria]])"
    }
   ]
  },
  {
   "title": "Hydration latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(vectorized_cloud_storage_read_path_chunk_hydration_latency_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of cloud client slowdowns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vectorized_cloud_client_num_slowdowns{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}[5m])) by ([[aggr_criteria]])"
    }
   ]
  },
  {
   "title": "Pending uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vectorized_ntp_archiver_pending{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}[5m])) by ([[aggr_criteria]])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Tiered Storage Cache Object Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(redpanda_cloud_storage_cache_space_files{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "Objects {{pod}}"
    },
    {
     "expr": "sum(redpanda_cloud_storage_cache_space_hwm_files{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "HWM {{pod}}"
    }
   ]
  },
  {
   "title": "Cloud storage readers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(redpanda_cloud_storage_readers{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Tiered Storage Cache Mean Object Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(redpanda_cloud_storage_cache_space_size_bytes{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"} / redpanda_cloud_storage_cache_space_files{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tiered Storage Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(redpanda_cloud_storage_cache_space_size_bytes{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "Objects {{pod}}"
    },
    {
     "expr": "sum(redpanda_cloud_storage_cache_space_hwm_size_bytes{instance=~\"[[node]]\",shard=~\"[[node_shard]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "HWM {{pod}}"
    }
   ]
  }
 ]
}